"""Basal ganglia habit-loop manager — Phase 3.

The basal ganglia are responsible for learning and executing procedural habits
— automatic, low-effort action sequences that bypass costly deliberative
planning.  In active-inference terms: when the organism has strong evidence
that an action will reliably reduce free energy (because it's worked many
times before), it does not need to run a full multi-step EFE rollout.
Instead it recalls the cached EFE estimate and executes at fraction of the
cost.

Biological analogue
-------------------
Striatum (caudate/putamen) accumulates evidence for repeated successful
actions.  Once a habit threshold is reached, the action is "chunked" into
a single motor program — fast, effortless, and metabolically cheap.
Habits are context-sensitive: they degrade under high stress (prefrontal
can override them) and become very strong at evolved stage with low
allostatic load.

Implementation
--------------
HabitRecord
    Tracks each named action: how many times it has been executed, rolling
    success fraction (how often it improved vitals), and a cached EFE
    estimate derived from the average outcome.

BasalGanglia
    Accumulates HabitRecords.  After ``HABIT_THRESHOLD`` successful
    executions, an action is considered habitual.  ``habit_efe()`` returns
    a cheap cost estimate instead of triggering a full EFE computation.
    Habits degrade under high allostatic load or explicit stress signals.

Integration
-----------
In ``pulse._decide()``:
1. Before generating proposals, check if the current recommended action is
   habitual.
2. If habitual and stress is below the override threshold, skip the full
   active_inference_step and return the habit EFE score directly.
3. Record the actual outcome vitals delta after execution so the habit
   record stays current.
4. Under overload or high allostatic load, always run full EFE regardless
   of habit status.

Metabolic savings
-----------------
Full EFE computation charges ~0.15 energy + ~0.03 heat.  Habit execution
charges ``HABIT_ENERGY_COST`` and ``HABIT_HEAT_COST`` (configurable),
typically ~70% cheaper.  This creates a strong incentive to develop good
habits — especially critical during the evolved stage.

Usage
-----
    bg = BasalGanglia()

    # After each executed action:
    bg.record_outcome(action_name, vitals_delta)

    # In _decide():
    if bg.is_habit(action_name):
        efe = bg.habit_efe(action_name, state)
        # skip full active_inference_step

    # Decay under stress each tick:
    bg.tick_decay(state)
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Any

from thermodynamic_agency.core.metabolic import MetabolicState


# ------------------------------------------------------------------ #
# Constants                                                           #
# ------------------------------------------------------------------ #

# Minimum successful executions before an action becomes habitual
HABIT_THRESHOLD: int = 6

# Maximum "strength" of a habit (0 = not a habit; 1 = fully habitual)
HABIT_MAX_STRENGTH: float = 1.0

# Minimum success-rate to maintain habit status (average positive outcomes)
HABIT_MIN_SUCCESS_RATE: float = 0.55

# How much habit strength decays per tick when allostatic load is high
# (load > HABIT_DECAY_AL_THRESHOLD → decay kicks in)
HABIT_DECAY_AL_THRESHOLD: float = 40.0
HABIT_DECAY_RATE: float = 0.04      # per tick above threshold, proportional to load

# Under free energy above this value the organism always runs full EFE
# regardless of habit status (stress overrides habits)
HABIT_FE_OVERRIDE: float = 50.0

# Metabolic cost of executing a known habit (vs. full EFE path)
HABIT_ENERGY_COST: float = 0.04   # energy consumed by habit execution
HABIT_HEAT_COST: float = 0.008    # heat generated by habit execution

# How quickly the cached EFE estimate is updated from new outcomes
_EFE_EMA_ALPHA: float = 0.30   # exponential moving average

# Rolling window for success rate calculation
_SUCCESS_WINDOW: int = 10


# ------------------------------------------------------------------ #
# Data types                                                          #
# ------------------------------------------------------------------ #

@dataclass
class HabitRecord:
    """Tracks one named action's habit state.

    Attributes
    ----------
    name:
        Action identifier (matches ActionProposal.name).
    execution_count:
        Total number of times this action has been executed.
    strength:
        Habit strength in [0, 1].  Grows with successful repetition.
    cached_efe:
        Exponentially-smoothed EFE estimate from past outcomes.  Lower = better.
    success_rate:
        Rolling fraction of executions that improved vitals.
    recent_outcomes:
        Circular buffer of recent outcome qualities (+1 = good, 0 = bad).
    """

    name: str
    execution_count: int = 0
    strength: float = 0.0
    cached_efe: float = 50.0     # starts pessimistic; converges down over time
    success_rate: float = 0.0
    recent_outcomes: list[int] = field(default_factory=list)

    def is_habitual(self) -> bool:
        """Return True if this action meets habit thresholds."""
        return (
            self.execution_count >= HABIT_THRESHOLD
            and self.success_rate >= HABIT_MIN_SUCCESS_RATE
            and self.strength >= 0.5
        )


@dataclass
class HabitSignal:
    """Return value from BasalGanglia.consult()."""

    action_name: str
    is_habit: bool
    estimated_efe: float           # habit EFE if is_habit; else full EFE required
    energy_cost: float             # metabolic cost of habit execution
    heat_cost: float
    strength: float                # current habit strength (0 if not a habit)
    reason: str = ""               # short explanation for logging


# ------------------------------------------------------------------ #
# Main class                                                          #
# ------------------------------------------------------------------ #

class BasalGanglia:
    """Habit-loop manager for procedural action caching.

    Maintains per-action HabitRecords and determines whether a candidate
    action can be executed as a cheap habit rather than via full EFE planning.
    """

    def __init__(self) -> None:
        self._habits: dict[str, HabitRecord] = {}

    # ------------------------------------------------------------------ #
    # Main interface                                                       #
    # ------------------------------------------------------------------ #

    def consult(
        self,
        action_name: str,
        state: MetabolicState,
    ) -> HabitSignal:
        """Check whether ``action_name`` can be executed as a habit.

        Parameters
        ----------
        action_name:
            The candidate action to check.
        state:
            Current metabolic state (read-only).

        Returns
        -------
        HabitSignal
            If ``is_habit`` is True, the caller may skip full EFE.
            ``energy_cost`` and ``heat_cost`` should still be applied.
        """
        record = self._habits.get(action_name)

        # Always run full EFE under high free energy
        if state.free_energy_estimate() >= HABIT_FE_OVERRIDE:
            efe_est = record.cached_efe if record else 50.0
            return HabitSignal(
                action_name=action_name,
                is_habit=False,
                estimated_efe=efe_est,
                energy_cost=HABIT_ENERGY_COST,
                heat_cost=HABIT_HEAT_COST,
                strength=record.strength if record else 0.0,
                reason="stress override — full EFE required",
            )

        if record is None or not record.is_habitual():
            return HabitSignal(
                action_name=action_name,
                is_habit=False,
                estimated_efe=record.cached_efe if record else 50.0,
                energy_cost=HABIT_ENERGY_COST,
                heat_cost=HABIT_HEAT_COST,
                strength=record.strength if record else 0.0,
                reason="no habit established — full EFE required",
            )

        return HabitSignal(
            action_name=action_name,
            is_habit=True,
            estimated_efe=record.cached_efe,
            energy_cost=HABIT_ENERGY_COST,
            heat_cost=HABIT_HEAT_COST,
            strength=record.strength,
            reason=(
                f"habit: n={record.execution_count} "
                f"sr={record.success_rate:.2f} "
                f"efe={record.cached_efe:.2f}"
            ),
        )

    def record_outcome(
        self,
        action_name: str,
        vitals_before: dict[str, float],
        vitals_after: dict[str, float],
    ) -> None:
        """Update the habit record for ``action_name`` after execution.

        Parameters
        ----------
        action_name:
            Name of the action that was executed.
        vitals_before:
            Metabolic state snapshot before action execution.
        vitals_after:
            Metabolic state snapshot after action execution.
        """
        if action_name not in self._habits:
            self._habits[action_name] = HabitRecord(name=action_name)

        record = self._habits[action_name]
        record.execution_count += 1

        # Evaluate outcome quality: positive = free energy went down
        outcome_quality = self._evaluate_outcome(vitals_before, vitals_after)
        success = 1 if outcome_quality > 0.0 else 0

        # Rolling success window
        record.recent_outcomes.append(success)
        if len(record.recent_outcomes) > _SUCCESS_WINDOW:
            record.recent_outcomes = record.recent_outcomes[-_SUCCESS_WINDOW:]
        record.success_rate = (
            sum(record.recent_outcomes) / len(record.recent_outcomes)
            if record.recent_outcomes else 0.0
        )

        # Update cached EFE with EMA (lower outcome quality → higher EFE estimate)
        outcome_efe = max(0.0, 50.0 - outcome_quality * 30.0)
        record.cached_efe = (
            _EFE_EMA_ALPHA * outcome_efe
            + (1.0 - _EFE_EMA_ALPHA) * record.cached_efe
        )

        # Grow habit strength when outcomes are good
        if success and record.execution_count >= HABIT_THRESHOLD:
            record.strength = min(
                HABIT_MAX_STRENGTH,
                record.strength + 0.07 * outcome_quality,
            )
        elif not success:
            record.strength = max(0.0, record.strength - 0.05)

    def tick_decay(self, state: MetabolicState) -> None:
        """Apply allostatic-load decay to all habit records.

        Call once per tick in the main pulse loop.  Under high allostatic
        load, habits slowly erode — the organism must re-learn them when
        chronic stress subsides.

        Parameters
        ----------
        state:
            Current metabolic state (allostatic_load is read).
        """
        al = state.allostatic_load
        if al <= HABIT_DECAY_AL_THRESHOLD:
            return

        excess = (al - HABIT_DECAY_AL_THRESHOLD) / (100.0 - HABIT_DECAY_AL_THRESHOLD)
        decay = HABIT_DECAY_RATE * excess

        for record in self._habits.values():
            record.strength = max(0.0, record.strength - decay)

    def all_habits(self) -> list[HabitRecord]:
        """Return all recorded habit records (sorted by strength descending)."""
        return sorted(self._habits.values(), key=lambda r: r.strength, reverse=True)

    def status(self) -> dict[str, Any]:
        """Summary dict for HUD / logging."""
        active = [r for r in self._habits.values() if r.is_habitual()]
        return {
            "total_tracked": len(self._habits),
            "active_habits": len(active),
            "habit_names": [r.name for r in active],
        }

    # ------------------------------------------------------------------ #
    # Private helpers                                                      #
    # ------------------------------------------------------------------ #

    @staticmethod
    def _evaluate_outcome(
        before: dict[str, float],
        after: dict[str, float],
    ) -> float:
        """Compute a scalar outcome quality from a vitals delta.

        Positive = free energy decreased (good).
        Uses a simple FE proxy matching MetabolicState.free_energy_estimate().

        Returns a value in roughly [-1, 1].
        """
        def _fe(v: dict[str, float]) -> float:
            deviations = (
                2.0 * max(0.0, 80.0 - v.get("energy", 80.0)) / 80.0
                + 1.5 * max(0.0, v.get("heat", 20.0) - 20.0) / 80.0
                + 1.0 * max(0.0, v.get("waste", 10.0) - 10.0) / 90.0
                + 1.8 * max(0.0, 85.0 - v.get("integrity", 85.0)) / 85.0
                + 1.4 * max(0.0, 80.0 - v.get("stability", 80.0)) / 80.0
            )
            return deviations / 7.7 * 100.0

        fe_before = _fe(before)
        fe_after = _fe(after)
        delta = fe_before - fe_after   # positive = improvement
        # Normalise to [-1, 1]
        return max(-1.0, min(1.0, delta / 20.0))
